# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AVPlayer视频播放库' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry', '~> 1.0.2'
  # Pods for AVPlayer视频播放库

  target 'AVPlayer视频播放库Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AVPlayer视频播放库UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
